"""Terraform/OpenTofu configuration generator for AumOS infrastructure.

Gap #12: Terraform integration — generates cloud-provider-specific .tf files
from module manifests and user-supplied variable values. Supports both
terraform and tofu CLI binaries.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

from aumos_common.observability import get_logger
from jinja2 import Environment, FileSystemLoader, StrictUndefined

logger = get_logger(__name__)

_TEMPLATES_DIR = Path(__file__).parent.parent / "templates" / "terraform"


class TerraformGenerator:
    """Generates Terraform/OpenTofu configuration files for AumOS cluster provisioning.

    Uses Jinja2 templates to produce provider-specific HCL configurations.
    Supports EKS, GKE, and AKS cloud providers.
    """

    SUPPORTED_PROVIDERS = ("eks", "gke", "aks")

    def __init__(
        self,
        provider: str,
        iac_binary: str = "terraform",
        templates_dir: Path = _TEMPLATES_DIR,
    ) -> None:
        """Initialize the TerraformGenerator.

        Args:
            provider: Cloud provider to generate for: eks, gke, or aks.
            iac_binary: IaC CLI binary to use: 'terraform' or 'tofu'.
            templates_dir: Directory containing Jinja2 .tf.j2 templates.

        Raises:
            ValueError: If provider is not in SUPPORTED_PROVIDERS.
        """
        if provider not in self.SUPPORTED_PROVIDERS:
            raise ValueError(f"provider must be one of {self.SUPPORTED_PROVIDERS}, got '{provider}'")

        self._provider = provider
        self._iac_binary = iac_binary
        self._templates_dir = templates_dir

        if templates_dir.exists():
            self._jinja_env = Environment(
                loader=FileSystemLoader(str(templates_dir)),
                undefined=StrictUndefined,
                autoescape=False,
            )
        else:
            self._jinja_env = None

    def generate(self, output_dir: Path, variables: dict[str, Any]) -> list[Path]:
        """Generate Terraform configuration files from templates.

        Args:
            output_dir: Directory to write generated .tf files.
            variables: Template variables to render into the configuration.

        Returns:
            List of generated file paths.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        generated: list[Path] = []

        if self._jinja_env is None:
            logger.warning("terraform_templates_dir_missing", templates_dir=str(self._templates_dir))
            generated.extend(self._generate_stubs(output_dir, variables))
            return generated

        provider_template_dir = self._templates_dir / self._provider
        if not provider_template_dir.exists():
            logger.warning("provider_template_dir_missing", provider=self._provider)
            generated.extend(self._generate_stubs(output_dir, variables))
            return generated

        for template_path in provider_template_dir.glob("*.tf.j2"):
            template_name = f"{self._provider}/{template_path.name}"
            template = self._jinja_env.get_template(template_name)
            rendered = template.render(**variables)
            output_file = output_dir / template_path.name.replace(".j2", "")
            output_file.write_text(rendered, encoding="utf-8")
            generated.append(output_file)
            logger.info("tf_file_generated", path=str(output_file))

        return generated

    def _generate_stubs(self, output_dir: Path, variables: dict[str, Any]) -> list[Path]:
        """Generate minimal stub .tf files when templates are unavailable.

        Args:
            output_dir: Directory to write stub files.
            variables: Variables to embed in the stub.

        Returns:
            List of generated stub file paths.
        """
        stub_content = f"""# Generated by AumOS Composable Installer
# Provider: {self._provider}
# Cluster: {variables.get('cluster_name', 'aumos-cluster')}
#
# Edit this file with your actual {self._provider.upper()} configuration.
# Run: {self._iac_binary} init && {self._iac_binary} plan

variable "cluster_name" {{
  default = "{variables.get('cluster_name', 'aumos-cluster')}"
}}

variable "kubernetes_version" {{
  default = "{variables.get('kubernetes_version', '1.29')}"
}}
"""
        stub_path = output_dir / "main.tf"
        stub_path.write_text(stub_content, encoding="utf-8")
        return [stub_path]

    def validate(self, terraform_dir: Path) -> bool:
        """Run IaC validate on the generated configuration.

        Args:
            terraform_dir: Directory containing the generated .tf files.

        Returns:
            True if validation passes, False otherwise.
        """
        init_result = subprocess.run(
            [self._iac_binary, "init", "-backend=false"],
            cwd=str(terraform_dir),
            capture_output=True,
            text=True,
            check=False,
        )
        if init_result.returncode != 0:
            logger.error("iac_init_failed", binary=self._iac_binary, stderr=init_result.stderr)
            return False

        validate_result = subprocess.run(
            [self._iac_binary, "validate"],
            cwd=str(terraform_dir),
            capture_output=True,
            text=True,
            check=False,
        )
        success = validate_result.returncode == 0
        if not success:
            logger.error("iac_validate_failed", binary=self._iac_binary, stderr=validate_result.stderr)
        return success
